//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lavie
    {
        public int LavieID { get; set; }
        public int SerialID { get; set; }
        public System.DateTime EntryDate { get; set; }
        public string ItemNumber { get; set; }
        public string ProductName { get; set; }
        public string GTIN { get; set; }
        public string BatchNumber { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> Layers { get; set; }
        public string GTINBarcode { get; set; }
        public string Barcode { get; set; }
        public string Remarks { get; set; }
        public string PalletID { get; set; }
        public Nullable<int> PrintedTimes { get; set; }
    }
}
